version: '3.3'

services:
  web:
    restart: always
    build: ./testproject
    expose:
      - "8000"
    volumes:
      - web-django:/usr/src/app
      - web-static:/usr/src/app/static
    environment:
      DEBUG: 'true'
    command: /usr/local/bin/gunicorn testproject.wsgi:application -w 2 -b :8000

volumes:
  web-django:
  web-static:
